export default [
  {
    name: 'Normal',
    immunes: ['Ghost'],
    weaknesses: ['Rock', 'Steel'],
    strengths: [],
  },
  {
    name: 'Fighting',
    immunes: ['Ghost'],
    weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy'],
    strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
  },
  {
    name: 'Flying',
    immunes: [],
    weaknesses: ['Electric', 'Rock', 'Steel'],
    strengths: ['Grass', 'Fighting', 'Bug'],
  },
  {
    name: 'Poison',
    immunes: ['Steel'],
    weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost'],
    strengths: ['Grass', 'Fairy'],
  },
  {
    name: 'Ground',
    immunes: ['Flying'],
    weaknesses: ['Grass', 'Bug'],
    strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
  },
  {
    name: 'Rock',
    immunes: [],
    weaknesses: ['Fighting', 'Ground', 'Steel'],
    strengths: ['Fire', 'Ice', 'Flying', 'Bug'],
  },
  {
    name: 'Bug',
    immunes: [],
    weaknesses: [
      'Fire',
      'Fighting',
      'Poison',
      'Flying',
      'Ghost',
      'Steel',
      'Fairy',
    ],
    strengths: ['Grass', 'Psychic', 'Dark'],
  },
  {
    name: 'Ghost',
    immunes: ['Normal'],
    weaknesses: ['Dark'],
    strengths: ['Psychic', 'Ghost'],
  },
  {
    name: 'Steel',
    immunes: [],
    weaknesses: ['Fire', 'Water', 'Electric', 'Steel'],
    strengths: ['Ice', 'Rock', 'Fairy'],
  },
  {
    name: 'Fire',
    immunes: [],
    weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
    strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
  },
  {
    name: 'Water',
    immunes: [],
    weaknesses: ['Water', 'Grass', 'Dragon'],
    strengths: ['Fire', 'Ground', 'Rock'],
  },
  {
    name: 'Grass',
    immunes: [],
    weaknesses: ['Fire', 'Grass', 'Poison', 'Flying', 'Bug', 'Dragon', 'Steel'],
    strengths: ['Water', 'Ground', 'Rock'],
  },
  {
    name: 'Electric',
    immunes: ['Ground'],
    weaknesses: ['Electric', 'Grass', 'Dragon'],
    strengths: ['Water', 'Flying'],
  },
  {
    name: 'Psychic',
    immunes: ['Dark'],
    weaknesses: ['Psychic', 'Steel'],
    strengths: ['Fighting', 'Poison'],
  },
  {
    name: 'Ice',
    immunes: [],
    weaknesses: ['Fire', 'Water', 'Ice', 'Steel'],
    strengths: ['Grass', 'Ground', 'Flying', 'Dragon'],
  },
  {
    name: 'Dragon',
    immunes: ['Fairy'],
    weaknesses: ['Steel'],
    strengths: ['Dragon'],
  },
  {
    name: 'Dark',
    immunes: [],
    weaknesses: ['Fighting', 'Dark', 'Fairy'],
    strengths: ['Psychic', 'Ghost'],
  },
  {
    name: 'Fairy',
    immunes: [],
    weaknesses: ['Fire', 'Poison', 'Steel'],
    strengths: ['Fighting', 'Dragon', 'Dark'],
  },
];
